import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "bootstrap/dist/css/bootstrap.min.css";
import "../styles/globals.scss";
import Header from "@/app/components/Header/Header";
import Footer from "@/app/components/Footer/Footer";
import PreloaderWrapper from "@/app/components/Preloader/PreloaderWrapper";
import SmoothScroll from "@/app/components/SmoothScroll/SmoothScroll";

const InterSans = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children}: { children: React.ReactNode }) {
  return (
    <html lang="en">
    <body className={InterSans.variable}>
      <Header/>
        <main>
          <SmoothScroll>{children}</SmoothScroll>
        </main>
      {/*<PreloaderWrapper><SmoothScroll>{children}</SmoothScroll></PreloaderWrapper>*/}
      <Footer/>
    </body>
    </html>
  );
}
